version: '3.8'

services:
  frontend:
    image: bloglist-front
    build:
      context: ./frontend
      dockerfile: dockerfile
    volumes:
      - ./frontend/:/usr/src/app
    container_name: bloglist-front
  backend:
    image: bloglist-back
    build:
      context: ./backend
      dockerfile: dockerfile
    volumes:
      - ./backend/:/usr/src/app
    container_name: bloglist-back
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: nginx-proxy
    depends_on:
      - frontend
    
